### ISSUE TITLE
Create dataset readers for all vision tasks

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4486]
- [ ] Conceptual Captions
 - [x] VQA 2.0 (@jiasenlu put this in #4461)
 - [ ] VCR (@jiasenlu put this in #4461)
 - [ ] RefCOCO
 - [ ] RefCOCO++
 - [ ] RefCOCOg
 - [ ] Flickr30k
 - [x] GQA
 - [ ] Visual Genome
 - [ ] COCO
 - [ ] Visual7W
 - [ ] GuessWhat
 - [ ] NLVR2 (part of #4481)
 - [x] SNLI-VE

**Comment by dirkgr** [comment]
We're still interested in this, and some of these are part of our [model wishlist](https://github.com/allenai/allennlp/issues?q=is%3Aissue+is%3Aopen+label%3AModels), but we don't have active work going on with these datasets that isn't being tracked elsewhere already.
