### ISSUE TITLE
Notebook Checklist

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#72]
- [x] Vocabulary

- [x] Data API - `Fields`, `Instances`, `Dataset`.

- [ ] `Iterators` and Training a model. 

- [ ] Tokens -> `Tokenizers` -> `TokenIndexers` Abstraction. 

- [ ] Writing a `DatasetReader` example.

- [ ] Writing a `Model`, differences between `torch.nn.Module`.

- [ ]  Why have `Params`? How to build things which run from JSON.

- [ ] `TokenEmbedders` -> `TextFields` -> representation Abstraction.

- [ ] `Seq2SeqEncoders` and `Seq2VecEncoders` and how to use them.

- [ ] How to make your model `Servable` and deploy a server via Docker.

**Comment by rsilveira79** [comment]
Looking forward to have more indo on this guys - keep doing the good work.

**Comment by schmmd** [comment]
Closing as this has evolved significantly since it was first created.
